openapi: 3.0.1
info:
  title: RiskPeek APIs
  version: 1.0.0
  description: Secure APIs for risk scoring and reporting

servers:
  - url: https://your-api-domain.com

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    RiskScoreRequest:
      type: object
      properties:
        legalName:
          type: string
        taxId:
          type: string
        annualRevenue:
          type: number
        creditScore:
          type: number
        amlStatus:
          type: string

    RiskScoreResponse:
      type: object
      properties:
        score:
          type: number
        confidence:
          type: string
        riskCategory:
          type: string
        factors:
          type: array
          items:
            type: string

paths:
  /api/risk-score:
    post:
      summary: Calculate a single risk score
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RiskScoreRequest'
      responses:
        '200':
          description: Risk score response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RiskScoreResponse'

  /api/bulk-risk-assessment:
    post:
      summary: Assess multiple records
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                assessments:
                  type: array
                  items:
                    $ref: '#/components/schemas/RiskScoreRequest'
      responses:
        '200':
          description: Bulk assessment response
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        legalName:
                          type: string
                        score:
                          type: number
                        riskCategory:
                          type: string

  /api/transaction-analysis:
    post:
      summary: Analyze stored transaction patterns
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Transaction analysis response
          content:
            application/json:
              schema:
                type: object
                properties:
                  summary:
                    type: string
                  anomalies:
                    type: array
                    items:
                      type: string
                  recommendations:
                    type: array
                    items:
                      type: string

  /api/reporting:
    get:
      summary: Retrieve aggregated reports
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Reporting data
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalAssessments:
                    type: integer
                  averageScore:
                    type: number
                  mostCommonRiskCategory:
                    type: string
                  assessments:
                    type: array
                    items:
                      $ref: '#/components/schemas/RiskScoreResponse'
